# Generated by Django 5.0.7 on 2024-07-28 12:27

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256, unique=True)),
                ('color', models.CharField(max_length=128)),
                ('screen_size', models.FloatField(verbose_name='screen size (inch)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('region', django_countries.fields.CountryField(max_length=2)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
    ]
